import { queryGranite } from '../services/graniteService';
import { assets, maintenanceRecords, alertsData } from '../data/mockData';

const SYSTEM_PROMPT = `You are GreenPulse AI Copilot, an intelligent assistant for a renewable energy operations platform monitoring solar and wind assets in Kutch and Banaskantha, Gujarat, India.

You have access to live data from 16 assets: 5 solar farms, 9 wind turbines, 2 hybrid sites.
Current alerts: WT-07 HIGH risk (gearbox degradation), WT-08 CRITICAL (offline), SF-04 MEDIUM (inverter temperature).
Current generation: ~570 MW total (solar: 540 MW, wind: 30 MW).
Performance score: 88.4%. Assets online: 14/16.

Guidelines:
- Reference specific asset data when answering
- Distinguish observed data from predictions
- Provide confidence levels where appropriate
- Be concise and actionable
- Never claim to directly control real grid infrastructure
- Label all data as prototype/demo data`;

// ─── Mock AI Responses ─────────────────────────────────────────────────────
const mockResponses: Record<string, string> = {
  default: `Based on the current platform data, I can see 14 of 16 assets are online with an overall performance score of 88.4%.

**Key priorities right now:**
1. **WT-07** (HIGH risk) — Gearbox vibration is 23% above baseline. Output is 18% below expected. Recommend inspection within 2–4 days.
2. **WT-08** — Currently offline. Critical drivetrain failure. Maintenance crew dispatched.
3. **SF-04 Deesa Solar Array** — Inverter INV-12 temperature trending high. Inspection recommended within 72 hours.

*Note: This response is generated by the GreenPulse AI mock engine. Connect IBM Granite credentials for enhanced AI responses.*`,

  wt07: `**WT-07 Performance Analysis** *(Prototype Data)*

**WHAT:** WT-07 is generating 1.68 MW vs expected 2.05 MW — an 18% deficit under current wind conditions (8.4 m/s).

**WHY:** Vibration sensor reads 0.89 (threshold: 0.65) — 37% above safe operating range. RPM has dropped to 10.4 vs rated 14.2 at current wind speed. This pattern is consistent with gearbox bearing wear or oil degradation. Health score: 61% (down from 81% 7 days ago).

**ACTION:** Schedule gearbox inspection within 2–4 days. Check gearbox oil viscosity, bearing temperatures, and gear mesh alignment. Consider reducing turbine load to 70% capacity until inspection.

**CONFIDENCE:** 87%

*Prototype data — simulated for demonstration purposes.*`,

  maintenance: `**Today's Maintenance Priorities** *(Prototype Data)*

🔴 **CRITICAL — WT-08** (Banaskantha)
Status: Offline. Emergency drivetrain replacement in progress. ETA: 7–14 days.

🟠 **HIGH — WT-07** (Banaskantha)  
Gearbox vibration 23% above baseline. Failure risk: 72%. Inspect within 2–4 days.

🟡 **MEDIUM — SF-04** (Deesa Solar Array)
Inverter INV-12 temperature rising. Efficiency -9% over 7 days. Inspect within 5–7 days.

🟡 **MEDIUM — WT-05** (Bhuj)
Blade vibration trending up. Inspect pitch control within 7–10 days.

🟢 **LOW — SF-02** (Mundra Solar Park)
Panel soiling detected. Schedule cleaning in 14–21 days.

*Prototype data — simulated for demonstration purposes.*`,

  forecast: `**Tomorrow's Generation Forecast** *(Prototype Data)*

**Solar:** Expected peak of 485 MW at approximately 12:30. Cloud cover forecast after 14:00 will reduce afternoon output by 12–14%.

**Wind:** Steady 28–32 MW throughout the day. Slight increase expected in northern cluster from northwest winds.

**Combined Daily:** ~4,280 MWh total (vs. today's ~4,340 MWh — 1.4% reduction due to afternoon cloud cover).

**Weather Impact:** Cloud coverage increases from 18% to 64% between 14:00–17:00, reducing solar irradiance from 820 W/m² to ~340 W/m².

**Grid Note:** Curtailment risk between 11:30–14:30 if storage is not pre-charged. Recommend pre-charging battery systems by 11:00.

*Prototype data — simulated for demonstration purposes.*`,

  grid: `**Grid Optimization Recommendation** *(Prototype Data)*

**CURRENT STATUS:**
- Generation: 572 MW | Grid Demand: 341 MW
- Export capacity available: 40 MW
- Storage available: 28 MW headroom

**ACTION: Prioritize Grid Export + Pre-Charge Storage**

Between 11:30–14:30, solar peak generation is forecast to reach 485 MW. Available grid export capacity is 440 MW — creating a potential 45 MW curtailment risk.

**Recommended steps:**
1. Begin pre-charging battery storage by 11:00 (28 MW available capacity)
2. Coordinate with grid operator to maximize export to 440 MW limit
3. After 14:00, reduce export as solar drops; switch to stored energy for evening demand peak

**Expected Benefit:** Reduce curtailment by ~43 MW (8% of peak generation).

**Confidence:** 89%

*Prototype data — simulated for demonstration purposes.*`,

  failure: `**Highest Failure Risk Asset** *(Prototype Data)*

**WT-08** — Banaskantha Wind T-08 (CRITICAL, currently offline)
- Health Score: 22% | Failure Risk: 96%
- Status: Drivetrain failure, turbine offline

**WT-07** — Banaskantha Wind T-07 (HIGH risk, still operating)
- Health Score: 61% | Failure Risk: 72%
- Vibration: 0.89 (37% above threshold)
- RPM: 10.4 (vs rated 14.2)
- Recommended action: Gearbox inspection within 2–4 days

*If you must prioritize resources, WT-07 requires immediate attention as it is still operating under degraded conditions and may escalate to failure.*

*Prototype data — simulated for demonstration purposes.*`,
};

function getMockResponse(message: string): string {
  const lower = message.toLowerCase();
  if (lower.includes('wt-07') || lower.includes('turbine') || lower.includes('underperform') || lower.includes('why')) return mockResponses.wt07;
  if (lower.includes('maintenance') || lower.includes('inspect') || lower.includes('priorit')) return mockResponses.maintenance;
  if (lower.includes('forecast') || lower.includes('tomorrow') || lower.includes('generation')) return mockResponses.forecast;
  if (lower.includes('grid') || lower.includes('export') || lower.includes('storage') || lower.includes('evening')) return mockResponses.grid;
  if (lower.includes('fail') || lower.includes('risk') || lower.includes('worst')) return mockResponses.failure;
  return mockResponses.default;
}

export async function getAIResponse(message: string): Promise<{ content: string; source: string }> {
  // Build context from live data
  const criticalAssets = assets.filter(a => a.riskLevel === 'CRITICAL' || a.riskLevel === 'HIGH');
  const contextSummary = `Live asset summary: ${assets.length} total assets. Online: ${assets.filter(a => a.status === 'online').length}. Critical/High risk: ${criticalAssets.map(a => a.assetId).join(', ')}. Current total generation: ${assets.reduce((s, a) => s + a.currentOutputMW, 0).toFixed(1)} MW.`;

  const fullPrompt = `${contextSummary}\n\nOperator question: ${message}`;

  const graniteResponse = await queryGranite(SYSTEM_PROMPT, fullPrompt);

  if (graniteResponse) {
    return { content: graniteResponse, source: 'IBM Granite LLM' };
  }

  // Fallback to mock
  return { content: getMockResponse(message), source: 'GreenPulse Mock Engine' };
}
